name: "Cronotermostato v2"
description: "Add-on per fornitura funzionalità cronotermostato"
version: "1.0.9"
slug: "cronotermostato_test"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  9081/tcp: 9081
homeassistant_api: true
hassio_role: admin
hassio_api: true
