name: "Cronotermostato"
description: "Add-on per fornitura funzionalità cronotermostato"
version: "1.0.19"
slug: "cronotermostato_test"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
hassio_role: admin
hassio_api: true

ingress: true
ingress_port: 9081
ingress_entry: "web"
ingress_stream: true

panel_icon: mdi:microsoft-visual-studio-code
startup: services

init: false
uart: true


webui: "[PROTO:http]://[HOST]:[PORT:9081]/web"



options:
  packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  config_path: str?
  packages:
    - str
  init_commands:
    - str